# Generated by Django 3.0.6 on 2020-05-28 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BTCUSDT',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('high', models.FloatField()),
                ('low', models.FloatField()),
                ('updated_at', models.DateTimeField()),
            ],
        ),
    ]
